### ISSUE TITLE
How to add arguments "trust_remote_code": "True" to hugginface model? 

### ISSUE THREAD

**Issue by cabisarri** [embedchain/embedchain#1239]
### 🚀 The feature

I wanted to test the local llm and embedder and below is my config, and I did some tracing, and i could not find how to add such argument "trust_remote_code": "True"  to it . below is my config yaml, could you help?

```
llm:
  provider: huggingface
  config:
    model: 'openbmb/MiniCPM-2B-sft-bf16'
    top_p: 0.8
embedder:
  provider: huggingface
  config:
    model: 'nomic-ai/nomic-embed-text-v1'
```

### Motivation, pitch

Let me know if there is a way to expand such easier either like model_kwargs: {trust_remote_code: True} to you class?
