### ISSUE TITLE
Cohere integration not working

### ISSUE THREAD

**Issue by pratikkotian04** [embedchain/embedchain#1247]
### 🐛 Describe the bug

I am loading the app using cohere api key , but the error still shows OpenAI key needed

Code :
os.environ["COHERE_API_KEY"] = "xxx"

app = App.from_config(config_path="/content/config.yaml")

Output:
KeyError                                  Traceback (most recent call last)
[<ipython-input-9-d8754c0a640b>](https://localhost:8080/#) in <cell line: 3>()
      1 os.environ["COHERE_API_KEY"] = "xxx"
      2 
----> 3 app = App.from_config(config_path="/content/config.yaml")

3 frames
[/usr/lib/python3.10/os.py](https://localhost:8080/#) in __getitem__(self, key)
    678         except KeyError:
    679             # raise KeyError with the original key value
--> 680             raise KeyError(key) from None
    681         return self.decodevalue(value)
    682 

KeyError: 'OPENAI_API_KEY'

**Comment by taranjeet** [comment]
Hey @pratikkotian04 thanks for reporting the issue.
I just checked the code and realized that this is happening because we dont have support for embeddings model via Cohere. (Issue #1248  for tracking)

For now, can you please try any other embedding model provider like hugging face or together ai?

Here is the complete config file. It includes cohere as the llm and hugging face as the embedding model.

```
llm:
  provider: cohere
  config:
    model: large
    temperature: 0.5
    max_tokens: 1000
    top_p: 1
embedder:
  provider: huggingface
  config:
    model: 'sentence-transformers/all-mpnet-base-v2'

```

Let me know if it doesnt work for you.
