### ISSUE TITLE
How can i set trust_remote_code = True ?

### ISSUE THREAD

**Issue by vivek9patel** [embedchain/embedchain#1380]
### 🐛 Describe the bug

I want to use nomic-embed-text-v1 model from huggingface. When I add it the app gives me following error:

`ValueError: Loading nomic-ai/nomic-embed-text-v1 requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option trust_remote_code=True to remove this error.`

After researching about this online, I got to know that I need to add trust_remote_code to True when initializing the SentenceTransformer. I believe embedchain uses this class internally but do we have config to set trust_remote_code on higher level?

**Comment by PranavPuranik** [comment]
I will pick this up...

**Comment by PranavPuranik** [comment]
Hi @vivek9patel ,

Pass this to your config once my PR is merged - 

```
embedder:
  provider: huggingface
  config:
    model: 'nomic-ai/nomic-embed-text-v1'
    model_kwargs:
      trust_remote_code: True
```
