### ISSUE TITLE
Add Github issue template of documentation

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#457]
### 🚀 The feature

Setup a issue template for documentation. Config can be

```
name: Documentation
description: Report an issue related to the Embedchain docs.
title: "DOC: <Please write a comprehensive title after the 'DOC: ' prefix>"

body:
- type: textarea
  attributes:
    label: "Issue with current documentation:"
    description: >
      Please make sure to leave a reference to the document/code you're
      referring to.
```

### Motivation, pitch

This will help us in making our docs better
