### ISSUE TITLE
1. LLm query did not find information in saved chroma 2. InvalidDimensionException: Embedding dimension 384 does not match collection dimensionality 1536

### ISSUE THREAD

**Issue by devopssii** [embedchain/embedchain#712]
### 🐛 Describe the bug

InvalidDimensionException: Embedding dimension 384 does not match collection dimensionality 1536 - this happend when i ty t load query saved db use agent form chroma and openai embeddings. How to create db with openaiembeddings?

**Comment by sidmohanty11** [comment]
Hey @devopssii , can you try this - 

```
from embedchain.embedder.openai import OpenAIEmbedder

# create your embedder
embedder = OpenAIEmbedder()

embedder.set_vector_dimension(xxx) # you need to set the embeddings dimension value in your vectorstore according to the embeddings function. For OpenAI its 1536

# use this embedder in your app
App(embedder=embedder)
```

This can probably also be caused by having the embeddings with different dimensions already stored inside the chroma db. You can fix that by removing the chroma `db` folder which contains the stored embeddings.

**Comment by ianderrington** [comment]
I get this error too, trying to add with an sitemap XML and using the [quickstart](https://docs.embedchain.ai/get-started/quickstart) mistral yaml with this embedder: 
```yaml
embedder:
  provider: huggingface
  config:
    model: 'sentence-transformers/all-mpnet-base-v2'
```
It is interesting/odd that it is exactly a factor of two wrong.

**Comment by taranjeet** [comment]
Hey @ianderrington , I tried the same config but I am not facing the error. Can you share more details like python version, your os and embedchain version?

```
➜  cat mistral.yaml
llm:
  provider: huggingface
  config:
    model: 'mistralai/Mistral-7B-v0.1'
    top_p: 0.5
embedder:
  provider: huggingface
  config:
    model: 'sentence-transformers/all-mpnet-base-v2'
```

**Comment by ianderrington** [comment]
Hi @taranjeet I just updated my error description: I found that it is due to trying to work with both open-source and open-ai model in the same chroma db...

**Comment by taranjeet** [comment]
Hey, thanks.
I will update this in the docs.
Meanwhile you can do pass the collection_name argument to have a separate collection

```
vectordb:
  provider: chroma
  config:
    collection_name: 'openai-app'
``` 

Here i have created a new config called `openai.yaml` and its has a new separate collection.

So the open source `mistral.yaml` will continue to use the default collection. Openai will use this.

let me know if this solves it.
