### ISSUE TITLE
azure_openai support stopped in embedders validation in v0.0.92 to 0.1.1

### ISSUE THREAD

**Issue by ghoshaishik505** [embedchain/embedchain#925]
### 🐛 azure_openai embedder: validation of config.yaml with azure_openai fails from in v0.0.92 to v0.1.1

When using azure openai's embedding functions, the config.yaml is 
```
llm:
  provider: azure_openai
  config:
    model: gpt-35-turbo
    deployment_name: your_llm_deployment_name
    temperature: 0.5
    max_tokens: 1000
    top_p: 1
    stream: false

embedder:
  provider: azure_openai
  config:
    model: text-embedding-ada-002
    deployment_name: you_embedding_model_deployment_name
```

The last few versions validate this yaml file, and throws Key 'provider' error: Or('openai', 'gpt4all', 'huggingface', 'vertexai') did not validate 'azure_openai')

Please add 'azure_openai' options in the validations.
